#!/usr/bin/env node
/**
 * Generate `packages/browser/deadhead.css`, in the ct.css spirit: drop one
 * stylesheet onto a page and the offending markup outlines itself and says
 * what it is.
 *
 * Two things make this work on `<head>`, which is normally invisible:
 * `head, head *  { display: block }` gives head elements a box to outline, and
 * `::after` on a void element like `<meta>` renders once it has one.
 *
 * Only selector-backed rules can appear here. A `kind: "document"` rule asks a
 * question CSS cannot ask ("does this start after byte 1024?"), and a rule
 * with `match: "logic"` is refined by code the stylesheet has no way to run —
 * that one is included, deliberately over-matching, and labelled as such.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { styleText } from "node:util";

import { ruleUrl, SITE_URL, type RuleMeta, type Severity } from "../packages/core/vocabulary.ts";
import { ROOT, rel } from "./rules-source.ts";
import { SVG_CAMEL } from "./svg-names.ts";

const IN = resolve(ROOT, "packages/rules/rules.json");
const OUT = resolve(ROOT, "packages/browser/deadhead.css");

const COLOUR: Record<Severity, string> = {
  harmful: "#d7263d",
  deprecated: "#e08700",
  unnecessary: "#2d7dd2",
};

/** CSS string escaping for the `content` property. */
export const cssString = (value: string): string =>
  `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/** Top-level comma split that respects quoted values: `[x="a,b"]` stays whole. */
const splitTopLevel = (selector: string): string[] => {
  const out: string[] = [];
  let depth = 0;
  let quote: string | null = null;
  let start = 0;
  for (let i = 0; i < selector.length; i++) {
    const c = selector[i];
    if (quote !== null) { if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'") quote = c;
    else if (c === "(" || c === "[") depth++;
    else if (c === ")" || c === "]") depth--;
    else if (c === "," && depth === 0) { out.push(selector.slice(start, i).trim()); start = i + 1; }
  }
  out.push(selector.slice(start).trim());
  return out.filter((s) => s !== "");
};

/**
 * `scope` becomes the CSS ancestor, mirroring what the walker does: a rule
 * scoped to `head` must not light up a `<meta>` someone put in the body.
 */
export const scoped = (meta: Pick<RuleMeta, "scope" | "selector">): string => {
  const prefix = meta.scope === "any" ? "" : `${meta.scope} `;
  // A rule's selector may be a comma list; the prefix distributes over it.
  const alternatives = splitTopLevel(meta.selector ?? "");
  const withCamel = alternatives.flatMap((alt) => {
    const tag = /^[a-z][a-z0-9-]*/.exec(alt)?.[0];
    const camel = tag === undefined ? undefined : SVG_CAMEL.get(tag);
    return camel === undefined ? [alt] : [alt, camel + alt.slice(tag!.length)];
  });
  return withCamel.map((part) => `${prefix}${part}`).join(",\n");
};

/** The stylesheet for a rule set. Pure: no I/O. */
export function renderCss(raw: RuleMeta[]): string {
  const rules = raw.filter((meta) => meta.selector !== null && meta.detectability !== "no");
  const skipped = raw.filter((meta) => meta.selector === null);

  const blocks = rules.map((meta) => {
    const selector = scoped(meta);
    const approximate = meta.match === "logic";
    const label = `${meta.severity} · ${meta.ruleId}${approximate ? " (approximate)" : ""}`;
    return `/* ${meta.ruleId} — ${meta.title}
   ${meta.description}
   ${ruleUrl(meta.ruleId)}${
     approximate
       ? "\n   Approximate: the rule refines this selector in code the stylesheet cannot run."
       : ""
   } */
${selector} {
  outline: 2px ${approximate ? "dashed" : "solid"} ${COLOUR[meta.severity]} !important;
  outline-offset: 2px;
}
${selector
  .split(",\n")
  .map((part) => `${part}::after`)
  .join(",\n")} {
  content: ${cssString(label)};
  display: inline-block;
  background: ${COLOUR[meta.severity]};
  color: #fff;
  font: 12px/1.4 ui-monospace, monospace;
  padding: 0 0.4em;
  margin-inline-start: 0.4em;
  border-radius: 3px;
  white-space: pre;
}`;
  });

  const css = `/* deadhead — generated by scripts/build-css.ts. Do not edit.
 *
 * Drop this into a page and anything it flags outlines itself:
 *   <link rel="stylesheet" href="deadhead.css">
 *
 * Every finding is explained at ${SITE_URL}/rules/<ruleId>.
 *
 * ${rules.length} of ${raw.length} rules are expressible as CSS.${
   skipped.length > 0
     ? `\n * Not here (no selector — they need code): ${skipped.map((m) => m.ruleId).join(", ")}.`
     : ""
 }
 */

/* <head> has no boxes to outline until it has a display. Keep <style> and
   <script> hidden, or their text content floods the top of the page. */
head,
head * {
  display: block;
}
head script,
head style,
head title {
  display: none;
}

${blocks.join("\n\n")}
`;

  return css;
}

if (import.meta.main) {
  const raw = await readRules();
  const css = renderCss(raw);
  const count = raw.filter((meta) => meta.selector !== null && meta.detectability !== "no").length;
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, css, "utf8");
  process.stdout.write(`${styleText("green", "✓")} ${count} rule(s) → ${rel(OUT)}\n`);
}

async function readRules(): Promise<RuleMeta[]> {
  try {
    const parsed = JSON.parse(await readFile(IN, "utf8")) as { rules: RuleMeta[] };
    return parsed.rules;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      process.stderr.write(
        `${styleText("red", "error")} ${rel(IN)} does not exist — run \`pnpm build\` first.\n`,
      );
      process.exit(2);
    }
    throw err;
  }
}
