#!/usr/bin/env node
/**
 * Generate `packages/browser/deadhead.css`, in the ct.css spirit: drop one
 * stylesheet onto a page and the offending markup outlines itself and says
 * what it is.
 *
 * Two things make this work on `<head>`, which is normally invisible:
 * `head, head *  { display: block }` gives head elements a box to outline, and
 * `::after` on a void element like `<meta>` renders once it has one.
 *
 * Only rules whose selector alone decides every finding can appear here. A
 * `kind: "document"` rule asks a question CSS cannot ask ("does this start
 * after byte 1024?"), and a `match` function refines its selector in code the
 * stylesheet cannot run: that selector is a pre-filter (`html` for
 * document/html-lang), and drawing it would outline markup the engine passes.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { styleText } from "node:util";

import type { Rule } from "../packages/core/engine.ts";
import { ruleUrl, SITE_URL, type RuleMeta, type Severity } from "../packages/core/vocabulary.ts";
import { loadRules, RulesNotBuiltError } from "../packages/rules/load.ts";
import { ROOT, rel } from "./rules-source.ts";
import { SVG_CAMEL } from "./svg-names.ts";

const OUT = resolve(ROOT, "packages/browser/deadhead.css");

const COLOUR: Record<Severity, string> = {
  harmful: "#d7263d",
  deprecated: "#e08700",
  unnecessary: "#2d7dd2",
};

/** CSS string escaping for the `content` property. */
export const cssString = (value: string): string =>
  `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/** Top-level comma split that respects quoted values: `[x="a,b"]` stays whole. */
const splitTopLevel = (selector: string): string[] => {
  const out: string[] = [];
  let depth = 0;
  let quote: string | null = null;
  let start = 0;
  for (let i = 0; i < selector.length; i++) {
    const c = selector[i];
    if (quote !== null) { if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'") quote = c;
    else if (c === "(" || c === "[") depth++;
    else if (c === ")" || c === "]") depth--;
    else if (c === "," && depth === 0) { out.push(selector.slice(start, i).trim()); start = i + 1; }
  }
  out.push(selector.slice(start).trim());
  return out.filter((s) => s !== "");
};

/**
 * `scope` becomes the CSS ancestor, mirroring what the walker does: a rule
 * scoped to `head` must not light up a `<meta>` someone put in the body.
 */
export const scoped = (meta: Pick<RuleMeta, "scope" | "selector">): string => {
  const prefix = meta.scope === "any" ? "" : `${meta.scope} `;
  // A rule's selector may be a comma list; the prefix distributes over it.
  const alternatives = splitTopLevel(meta.selector ?? "");
  const withCamel = alternatives.flatMap((alt) => {
    const tag = /^[a-z][a-z0-9-]*/.exec(alt)?.[0];
    const camel = tag === undefined ? undefined : SVG_CAMEL.get(tag);
    return camel === undefined ? [alt] : [alt, camel + alt.slice(tag!.length)];
  });
  return withCamel.map((part) => `${prefix}${part}`).join(",\n");
};

/**
 * Whether the stylesheet can carry a rule: its selector alone decides every
 * finding. A module exporting only `fixable` vetoes fixes, not findings, so
 * its rule stays in.
 */
export const selectorDecides = (rule: Pick<Rule, "meta" | "match" | "check">): boolean =>
  rule.meta.selector !== null &&
  rule.meta.detectability !== "no" &&
  rule.match === undefined &&
  rule.check === undefined;

/** The stylesheet for a rule set. Pure: no I/O. */
export function renderCss(all: Rule[]): string {
  const rules = all.filter(selectorDecides).map((rule) => rule.meta);
  const skipped = all.filter((rule) => !selectorDecides(rule)).map((rule) => rule.meta.ruleId);

  const blocks = rules.map((meta) => {
    const selector = scoped(meta);
    const label = `${meta.severity} · ${meta.ruleId}`;
    return `/* ${meta.ruleId} — ${meta.title}
   ${meta.description}
   ${ruleUrl(meta.ruleId)} */
${selector} {
  outline: 2px solid ${COLOUR[meta.severity]} !important;
  outline-offset: 2px;
}
${selector
  .split(",\n")
  .map((part) => `${part}::after`)
  .join(",\n")} {
  content: ${cssString(label)};
  display: inline-block;
  background: ${COLOUR[meta.severity]};
  color: #fff;
  font: 12px/1.4 ui-monospace, monospace;
  padding: 0 0.4em;
  margin-inline-start: 0.4em;
  border-radius: 3px;
  white-space: pre;
}`;
  });

  const css = `/* deadhead — generated by scripts/build-css.ts. Do not edit.
 *
 * Drop this into a page and anything it flags outlines itself:
 *   <link rel="stylesheet" href="deadhead.css">
 *
 * Every finding is explained at ${SITE_URL}/rules/<ruleId>.
 *
 * ${rules.length} of ${all.length} rules are expressible as CSS.${
   skipped.length > 0
     ? `\n * Not here (code decides them, so a selector would over-match): ${skipped.join(", ")}.`
     : ""
 }
 */

/* <head> has no boxes to outline until it has a display. Keep <style> and
   <script> hidden, or their text content floods the top of the page. */
head,
head * {
  display: block;
}
head script,
head style,
head title {
  display: none;
}

${blocks.join("\n\n")}
`;

  return css;
}

if (import.meta.main) {
  const all = await readRules();
  const css = renderCss(all);
  const count = all.filter(selectorDecides).length;
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, css, "utf8");
  process.stdout.write(`${styleText("green", "✓")} ${count} rule(s) → ${rel(OUT)}\n`);
}

async function readRules(): Promise<Rule[]> {
  try {
    return await loadRules();
  } catch (err) {
    if (err instanceof RulesNotBuiltError) {
      process.stderr.write(`${styleText("red", "error")} ${err.message}\n`);
      process.exit(2);
    }
    throw err;
  }
}
