/**
 * Writes packages/eslint-plugin/entities.ts, HTML's named character
 * references, from WHATWG's entities.json. The ESLint adapter decodes with it
 * because es-html-parser returns attribute values and text as written.
 *
 * Usage: node scripts/build-entities.ts [path-or-url]
 * Default: https://html.spec.whatwg.org/entities.json. Not part of `pnpm build`:
 * the table changes only when the HTML Standard adds a name.
 */
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";

const SOURCE = "https://html.spec.whatwg.org/entities.json";
const OUT = "packages/eslint-plugin/entities.ts";

const from = process.argv[2] ?? SOURCE;
const text = /^https?:/.test(from) ? await (await fetch(from)).text() : await readFile(from, "utf8");
const table = JSON.parse(text) as Record<string, { characters: string }>;
const entries = Object.entries(table)
  .map(([name, { characters }]) => [name.slice(1), characters] as const)
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
if (entries.length < 2000) throw new Error(`${from}: only ${entries.length} entries`);

const digest = createHash("sha256").update(text).digest("hex").slice(0, 16);
const body = entries.map(([name, characters]) => `  ${JSON.stringify(name)}: ${JSON.stringify(characters)},`).join("\n");
await writeFile(
  OUT,
  `// Generated by scripts/build-entities.ts from ${SOURCE} (sha256 ${digest}). Do not edit.

/**
 * HTML's named character references: the name after "&", with ";" where the
 * table has it (106 legacy names also appear without), to the characters.
 */
export const ENTITIES: Readonly<Record<string, string>> = {
${body}
};
`,
);
console.log(`${OUT}: ${entries.length} names (sha256 ${digest})`);
