#!/usr/bin/env node
/**
 * Compile `content/rules/**\/*.md` into `packages/rules/rules.json`.
 *
 * The markdown is the source of truth; this is the only thing that turns it
 * into something a runtime can load. The output is gitignored on purpose —
 * a checked-in generated file is a second source of truth waiting to drift.
 *
 * Prose is deliberately *not* emitted. Every finding links to
 * https://deadhead.cevdet.ch/rules/<ruleId> for the explanation, and the bookmarklet
 * inlines this file into a single IIFE, so anything in here is bytes in a
 * URL bar.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { styleText } from "node:util";
import { pathToFileURL } from "node:url";

import { META_KEYS, type RuleMeta } from "./schema.ts";
import { ROOT, loadRules, printDiagnostics, rel } from "./rules-source.ts";

const OUT = resolve(ROOT, "packages/rules/rules.json");
const REGISTRY_OUT = resolve(ROOT, "packages/rules/registry.gen.ts");

/** Fixed key order, so a one-field change is a one-line diff when inspected. */
function ordered(meta: RuleMeta): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of META_KEYS) out[key] = meta[key];
  return out;
}

/**
 * The compiled rules.json text. Pure: no I/O beyond reading the markdown
 * source, and no write — `import.meta.main` below owns the file write so
 * importing this module never rewrites the shared, gitignored output.
 */
export async function buildRulesJson(): Promise<string> {
  const { rules, diagnostics } = await loadRules();
  if (diagnostics.length > 0) {
    printDiagnostics(diagnostics);
    throw new Error(`${diagnostics.length} problem(s); refusing to build rules.json`);
  }
  // Sorted by ruleId (loadRules guarantees it) and newline-terminated: the
  // output is reproducible, so a rebuild that changes nothing produces zero
  // bytes of diff.
  return `${JSON.stringify({ schemaVersion: 1, rules: rules.map((rule) => ordered(rule.meta)) }, null, 2)}\n`;
}

/**
 * A module that imports every logic entry statically and exports the full rule set.
 *
 * Build-time dynamic import decides which names exist: element modules may
 * export `fixable` alone, and a named import of a missing export fails at link
 * time, so only names the module actually exports are imported.
 */
export async function renderRegistry(metas: RuleMeta[]): Promise<string> {
  const imports: string[] = [];
  const entries: string[] = [];
  for (let i = 0; i < metas.length; i++) {
    const meta = metas[i]!;
    const needs = meta.match === "logic" || meta.kind === "document";
    if (!needs) {
      entries.push(`  { meta: ${JSON.stringify(meta)} },`);
      continue;
    }
    const file = resolve(ROOT, "packages/rules/logic", `${meta.ruleId}.ts`);
    const module: Record<string, unknown> = await import(pathToFileURL(file).href);
    if (meta.kind === "document") {
      imports.push(`import { check as l${i} } from "./logic/${meta.ruleId}.ts";`);
      entries.push(`  { meta: ${JSON.stringify(meta)}, check: l${i} },`);
      continue;
    }
    const parts: string[] = [];
    if (typeof module["match"] === "function") {
      imports.push(`import { match as l${i}m } from "./logic/${meta.ruleId}.ts";`);
      parts.push(`match: l${i}m`);
    }
    if (typeof module["fixable"] === "function") {
      imports.push(`import { fixable as l${i}f } from "./logic/${meta.ruleId}.ts";`);
      parts.push(`fixable: l${i}f`);
    }
    entries.push(`  { meta: ${JSON.stringify(meta)}${parts.length > 0 ? `, ${parts.join(", ")}` : ""} },`);
  }
  return `// Generated by scripts/build-rules.ts from content/rules. Do not edit.
import type { Rule } from "../core/engine.ts";
${imports.join("\n")}

export const RULES: Rule[] = [
${entries.join("\n")}
];
`;
}

if (import.meta.main) {
  let json: string;
  try {
    json = await buildRulesJson();
  } catch (err) {
    process.stderr.write(`\n${styleText("red", (err as Error).message)}\n`);
    process.exit(1);
  }
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, json, "utf8");
  const count = (JSON.parse(json) as { rules: unknown[] }).rules.length;
  process.stdout.write(`${styleText("green", "✓")} ${count} rule(s) → ${rel(OUT)}\n`);
  const metas = (JSON.parse(json) as { rules: RuleMeta[] }).rules;
  await writeFile(REGISTRY_OUT, await renderRegistry(metas), "utf8");
  process.stdout.write(`${styleText("green", "✓")} ${metas.length} rule(s) → ${rel(REGISTRY_OUT)}\n`);
}
