/**
 * The runnable rule set. `registry.gen.ts` is generated by `pnpm build` from
 * content/rules, with every logic module imported statically, so loading is one
 * module graph: no per-rule dynamic import, no top-level await for consumers.
 */

import type { Rule } from "../core/engine.ts";

export class RulesNotBuiltError extends Error {}

export async function loadRules(): Promise<Rule[]> {
  try {
    return (await import("./registry.gen.ts")).RULES;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ERR_MODULE_NOT_FOUND") {
      throw new RulesNotBuiltError("packages/rules/registry.gen.ts does not exist. It is generated from content/rules — run `pnpm build`.");
    }
    throw err;
  }
}
